# Generated by Django 5.0.1 on 2024-02-28 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('professor', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='CoopReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_updated', models.DateField(auto_now=True)),
                ('job_title', models.CharField(default=None, max_length=80)),
                ('term', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('num_prev_workterms', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('interview_difficulty', models.IntegerField()),
                ('skill_building', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('mentorship', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.company')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_updated', models.DateField(auto_now=True)),
                ('job_title', models.CharField(default=None, max_length=80)),
                ('term', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('num_prev_workterms', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('interview_difficulty', models.IntegerField()),
                ('skill_building', models.IntegerField()),
                ('culture', models.IntegerField()),
                ('mentorship', models.IntegerField()),
                ('comments', models.CharField(max_length=1000)),
                ('funding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('research_group_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.researchgroup')),
                ('user_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
