# Generated by Django 5.0.1 on 2024-02-29 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_term_coopreview_termtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopreview',
            old_name='company_ID',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='researchreview',
            old_name='research_group_ID',
            new_name='research_group',
        ),
    ]
