# Generated by Django 5.0.1 on 2024-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
