# Generated by Django 5.0.1 on 2024-01-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_first_name_user_full_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UTJUser',
        ),
    ]
