# Generated by Django 5.0.1 on 2024-01-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UTJUser',
            new_name='User',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
