# Generated by Django 5.0.1 on 2024-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_submission',
            field=models.DateTimeField(default=None),
        ),
    ]
