# Generated by Django 5.0.1 on 2024-01-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_last_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_submission',
            field=models.DateTimeField(default=-1),
        ),
    ]
