# Generated by Django 5.0.1 on 2024-01-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_last_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_submission',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
